### ISSUE TITLE
RT-AX86U koolshare梅林改版固件:388.1，下载订阅源URL信息失败

### ISSUE THREAD

**Issue by xiayanfire** [vxiaov/vClash#40]
**Bug描述**
在"节点管理">"PROXY组"添加订阅的url，提示下载订阅源URL信息失败。
测试了好几个url，这些url在x86 windows 客户端都能正常获取到配置文件，和节点。

**Bug重现**
描述触发Bug的步骤:
1. 访问 '...' 页面
2. 点击 '...' tab页面
3. 点击 '...' 功能
4. Bug出现了。

**截图**
如果可以，请附上截图，截图记得将敏感信息打上马赛克。
![1709792469054](https://github.com/vxiaov/vClash/assets/38719247/be99d86f-4b5d-4be0-b6c9-d0f5e20ef7cc)

**路由器信息:**
您的路由器基本信息(反馈开发者帮您分析问题用):
| system : Linux RT-AX86U-3348 4.1.52 aarch64 ASUSWRT-Merlin-KoolShare|
| rom    : RT-AX86U:koolshare梅林改版固件:388.1|
| memory : free: 310.60 MB,total: 912.08 MB,usage:  65.95%|
| /jffs  : free:  15.00 MB,total:  47.00 MB,usage:  68.08%|
+---------------------------------------------------------------+
|>> vClash当前正在使用的软件版本:                                   << |
|              vClash :                                         |
|       clash_premium : 2023.08.17_linux_arm64                  |
|                  yq : 4.13.2                                  |
|                  jq : jq-1.5rc2-245-g7b81a83-dirty            |
|>> vClash初始安装包自带的软件版本(分析是否个人更改过):                                   << |
|              vClash : v2.3.7                                  |
|       clash_premium : 2021.09.15_v1.7.1                       |
|                  yq : 4.13.2                                  |
|                  jq : jq-1.5rc2-245-g7b81a83-dirty            |
+---------------------------------------------------------------+
vClash的转发规则(iptables -t nat -S | grep clash),分析转发规则是否正常:
-N clash
-N clash_dns
-A PREROUTING -s 192.168.0.0/24 -p tcp -j clash
-A PREROUTING -s 192.168.0.0/24 -p udp -m udp --dport 53 -j clash_dns
-A PREROUTING -s 192.168.0.0/24 -p tcp -m tcp --dport 53 -j clash_dns
-A clash -d 10.0.0.0/8 -j RETURN
-A clash -d 127.0.0.0/8 -j RETURN
-A clash -d 169.254.0.0/16 -j RETURN
-A clash -d 172.16.0.0/12 -j RETURN
-A clash -d 192.168.0.0/24 -j RETURN
-A clash -s 192.168.0.0/24 -p tcp -j REDIRECT --to-ports 3333
-A clash_dns -p udp -m udp --dport 53 -j REDIRECT --to-ports 1053
-A clash_dns -p tcp -m tcp --dport 53 -j REDIRECT --to-ports 1053
+---------------------------------------------------------------+

**Comment by Awkee** [comment]
解析这个问题目前原因很多，我最近的更新已经删除了解析URI链接功能，这样就去除了因为我个人编写的解析工具原因导致解析错误。
另外，也迫使大家使用yaml格式配置节点，对于不知道如何使用配置yaml格式，建议购买机场时挑选提供yaml格式订阅链接的。
